### PR TITLE
Getting run-tests.sh to work on macOS

### PR DESCRIPTION
**Pull request by Alex-Vasile**
Fixes the half of the issues Brough up in #109.

Replaced head with sed so that commands works on macOS.

Also added description of what the entire command does.

### CODE REVIEW

**Comment by mk270** [comment]
ah thanks - I'll have a look

**Comment by mk270** [comment]
Hi @Alex-Vasile ... the code you've pushed doesn't always do the right thing; could you change it to:

    sed -e :a -e '$q;N;20,$D;ba' | sed -e '$ d'

(which I think does the right thing portably; obviously long-term we need a better solution to this, which is barely legible)

**Comment by Alex-Vasile** [comment]
@mk270, The first commit in the PR broke things by mistake, my second commit should have fixed it (It was an issue with the tail command).

I tried replacing
`tail -n +19 | sed -e '$ d'`
with
`sed -e :a -e '$q;N;20,$D;ba' | sed -e '$ d'`
but all tests fail on macOS. I'm not entirely sure what the issue is, but I have attached the [output.txt](https://github.com/mk270/whitakers-words/files/5434129/output.txt).

**Comment by mk270** [comment]
what we need is a portable implementation of "give me the last 19 lines of output". Since the interface of `tail` was unaccountably changed, that's become harder.

I don't want to give up on portability, but I have no means of testing this stuff on MacOS. We might be reduced to reimplementing `tail -19` in Ada at this rate.

**Comment by Alex-Vasile** [comment]
What do you mean, or what change for tail are you referring to?

But yes, the shell scripts are a bit of a trouble for cross-platform support.

I tested your suggested change (`sed -e :a -e '$q;N;20,$D;ba' | sed -e '$ d'`) on Ubuntu 20.04, and I am getting the same issue as on macOS. However, `tail -n +19 | sed -e '$ d'` (what is currently in this PR) works.

Does it work on Windows? (I haven't gotten gnat running on my windows installation yet).

If it is, we should consider going it with for now, work towards releasing binaries for v1.98, and come back for a longer term solution after.

**Pull request closed without merging**
