### PR TITLE
darkestkhan

### PR DESCRIPTION
**Pull request by darkestkhan**
Rest of style checks.
There are still issues with identifiers (should follow standard Ada convention of Proper_Names_With_Underscore_Or_SRS_Acronyms), lines shouldn't be longer than 80 chars and inclusion of t in style checks shouldn't generate MBs of warnings but these can be resolved with time.

### CODE REVIEW

**Comment by mk270** [comment]
Hi, is it possible to leave the case change commits out? The more style changes you make, the more work other developers have to go to to adapt their dev environments to keep up.

You've based later changes that aren't purely stylistic on your re-styled versions, which links the decision to merge one with the decision to merge the other, so they can't be considered on their independent merits.

**Comment by darkestkhan** [comment]
Why do other devs have to adapt they dev environments just due to case changes?

**Comment by mk270** [comment]
Because some dev environments (e.g., Emacs ada-mode) automatically change the case of identifiers in source code you edit. I know, it's ridiculous. But it took me a long time to work out how to switch it off.

**Comment by darkestkhan** [comment]
This sounds like an invalid behavior or misconfiguration (when I used emacs with ada-mode it changed case of identifiers correctly).

Problem is that I'm too deep into changes with cases - basically would have to do all that work again.

**Comment by mk270** [comment]
> Problem is that I'm too deep into changes with cases - basically would have to do all that work again

This is my point

**Comment by darkestkhan** [comment]
"Because some dev environments (e.g., Emacs ada-mode) automatically change the case of identifiers in source code you edit."

Guess how GNAT Programming Studio changes identifiers automatically...  to standard Ada practice.

I don't see what is your point - outside of not making source more readable.

**Comment by Fuco1** [comment]
If we are going to do a lot of these style edits, then maybe we should wait until it's all done and then start contributions from that base? 

Should I now look into parse module or should I wait until the reformatting is over?

@darkestkhan I think the point was also that this PR is too big and it changes more than one thing.

Also, I think having merge commits in a PR is really bad practice, it will lead to unreadable history.  Do you plan to rebase before merge?

**Comment by darkestkhan** [comment]
@Fuco1 I always rebase before merge - especially when there are commits ahead. I merge from my other branch on which I actively do development (dev branch) into darkestkhan branch.

I always rebase before merges - but for some odd reason I still got merge conflict.

As for style changes before working on parse - I can always do full style change on parse asap.

It shouldn't take more than 3h for entire parse.ad{b,s} + collateral changes to other files.

**Comment by mk270** [comment]
I'd rather not have any more style changes - the code is full of global variables, unmodular, is hard to understand, etc - we shouldn't be worrying about indentation!

**Comment by darkestkhan** [comment]
But indentation is already done O_o
Also the code is not that hard - there is some logic behind it (and TLA syndrome... getting rid of this one is taking a lot of time)

**Comment by mk270** [comment]
by hard to understand, i mainly meant that in some routines, there are twenty or thirty variables in play - I agree that it's fairly simplistic in other ways

**Comment by mk270** [comment]
Ok, I've merged this stuff, though I'm really skeptical about the case changes, as stated

**Pull request merged**
