### PR TITLE
Improve the build system, search path for input data

### PR DESCRIPTION
**Pull request by asarhaddon**
Hello.
This request makes the build system more configurable, and allow installation of the executables and the data into distinct read-only directories. This is a prerequisite for a new Debian package.
The commits are either trivial or heavily overlapping, so several independent requests do not make much sense for now.  Could you please give them a quick review and tell me if/how I should rewrite the history and/or cancel some changes?
The final state builds and passes the tests from the Makefile. The new variables seem to have the desired effect, and reproduce the existing behaviour when unset.
Thanks.

### CODE REVIEW

**Comment by calumapplepie** [comment]
This would close #108

**Comment by mk270** [comment]
Thank you very much for all this; the build "system" was never terribly good, and largely was hacked together by me in ignorance of how to "go with the grain" of the way Ada would normally do it.

I hope this is a big step towards improving automated builds, too!

I assume you're happy for your contributions to be distributed under the same terms as WORDS itself?

**Comment by asarhaddon** [comment]
Thanks for answering so quickly.

Yes, I give my contribution with the same license than the existing sources.

I have a few questions about the project structure.

* Why are there two standard projects, `commands.gpr` and `tools.gpr`? It is most probably possible to merge them and select the built programs on the `gprbuild` command line
(there may be good reasons to keep the sources under distinct directories).

* Why are there three libraries? I understand that a separate library would make the functions available for programs other than `words`, but I fail to understand the need for 3 libraries (there may be good reasons to keep the sources under distinct directories and/or distinct Ada packages).

**Comment by mk270** [comment]
I believe the commands/tools distinction was originally that "tools" were programs for maintaining the data files as distributed in the original source archive, whereas "commands" consumed those files programmatically. That is, you could dispense with "tools" if you never intended to modify the databases. It was never particularly rigid. It may be that the "tools" originated from a separate source archive. As you say, there may be good reasons for keeping them separate.

The three libraries were separated out by @darkestkhan ; there was a need for *some* separation to make the code organisation intelligible, and he separated out what concerns he could.

**Comment by asarhaddon** [comment]
For executables:

Currently, Makefile provides:
* a target building all commands
* no way to build tools other than `sorter`.  Someone probably uses or used plain `gprbuild` to build them, but gprbuild ignores things known to Makefile (selection of the library kind, generated sources..).
* a separate target for each command (and the `sorter` tool).   These targets are probably invoked indirectly by everyone in the end (the main program requires the dictionaries, and their generation requires most commands and `sorter`.  Each target invokes `gprbuild`, which computes the Ada dependency graph again and again.
On my machine, 'make all' spends a comparable amount of time in `gprbuild` sequentially checking again and again that all Ada objects are up-to-date, than in `gcc` doing actual compilations.

I suggest to have only one `tools.gpr` project building all executables, so that `gprbuild` computes the dependency graph only once, then efficiently drives all Ada compilation in parallel.
Else, a similar result can be achieved with an aggregate project depending on `commands.gpr` and `tools.gpr`, but this increases the overall complexity. 
This does not prevent a future Makefile `install` target to handle tools and commands differently, or the sources living in separate subdirectories.

For libraries:

I am not questioning the Ada package hierarchy, which is the right tool in order to make the source code organisation intelligible. I am only talking about the resulting binary objects.

A static library is duplicated in each executable using it, so currently the libraries have no effect.  I understand that the intent is to prepare shared libraries/dynamic linking, so that some binary code is shared among all command and tools (and possibly future executable written in other languages by other people).  My impression (based only on what I have seen so far) is that most such executables will (directly or indirectly) use all three libraries, so that there is no gain in three libraries compared to one library. And this increases the overall complexity.

Another aspect is that you do not want to distribute a library with a generic name as `libsupports_utils`.  A library often contains one top-level Ada packages in order to limit namespace pollution in large projects (in Ada sources, but also at link time, since the  Ada package name is a component of the link symbol).

I suggest a library named `libwhitakers_words`, containing packages named
* `whitakers_words` (top-level, only for the namepace issue in larger projects),
* `whitakers_words-support_utils`, `whitakers_words-latin_utils` and `whitakers_words-words_engine` (code organisation),
* `whitakers_words-support_utils-*` and so on (actual code)

**Pull request merged**
