### PR TITLE
DICTLINE.GEN: Add missing newline (#92)

### PR DESCRIPTION
**Pull request by ids1024**

### CODE REVIEW

**Comment by mk270** [comment]
thanks - note that this triggers a problem which prevents the programme from running; it might be a bug

```raised CONSTRAINT_ERROR : words_engine-list_sweep.adb:123 discriminant check failed```

**Comment by ids1024** [comment]
Hm. Honestly, I'm not familiar enough with the format of this file to know exactly how it should be, so I don't know if there's anything wrong with my change (which changes it to match the `DICTLINE.GEN.csv` from the other PR). I don't know if you're more familiar with it.

How did you get that error message?

it runs fine for me with a few test words, but results in `Exception in PARSE_LINE processing regina gravi iamdudum saucia cura`  when run on `test/aeneid_bk4.txt`.

**Comment by mk270** [comment]
It looks like we have a packaging error; one of the data files is actually programmatically generated from one of the others, and this isn't captured in the Makefile. It is run through a tricky sort programme that knows about Latin's collation rules (i.e., I = J, U = V), and the results are cached in the repo. There were good reasons for this in the 1980s, but I reckon they no longer apply and that we should change this; after the change we'll have another look at this PR.

**Comment by mk270** [comment]
ok - build system fixed, test system modified to be less sensitive to changes in the dictionary. merged

**Comment by mk270** [comment]
thanks for sorting this out @ids1024

**Pull request merged**
