### PR TITLE
Change set - prevents several exceptions; dictionary fixes

### PR DESCRIPTION
**Pull request by spr93**
The descriptions and diffs should be straightforward.  They do the following:

(i) fix exceptions that occur in both Whitaker's 1.97FC and your current repo; 
(ii) correct dictionary errors;
(iii) remove -gnat05 flag from the .gprs, which lets the gprs be used on an out-of-the-box GNAT 2019 macOS install.

Hope most or all of these are helpful.

### CODE REVIEW

**Comment by mk270** [comment]
Thank you for this - are you happy for you contributions to be licensed under the same terms as Whitaker's Words itself?

**Comment by spr93** [comment]
Yes.

**Comment by mk270** [comment]
Thank you very much - I hadn't realised who you were until now.

I appreciate you've probably gone to a *lot* of effort to separate out the divergence between your copy of the WORDS codebase and this one.

It's also very kind of you to split up the changes into logical commits, which assorts well with the availability of resource to deal with them - they are being reviewed and merged piecemeal.

**Comment by mk270** [comment]
Even though it's not particularly onerous, this PR has had the beneficial side-effect of motivating me to get a better test rig and some assistance with testing.  I've started merging it in.

**Comment by calumapplepie** [comment]
Tests are failing: I recommend updating the "expected" entries in the testing folder.

**Pull request closed without merging**
