### PR TITLE
Inflections package - separate Quality_Record_IO.

### PR DESCRIPTION
**Pull request by darkestkhan**

### CODE REVIEW

**Comment by mk270** [comment]
Thank you once again - I must say I'm in two minds about this; the N, V terminology is standard in linguistics, and certainly was what I used to use when working on treebanks myself.

Have a look at the nodes in the diagram at https://en.wikipedia.org/wiki/X-bar_theory#A_full_sentence , for example

**Comment by darkestkhan** [comment]
Any other standard terminology in linguistics? (like for adjective or preposition)

**Comment by mk270** [comment]
It's not worth keeping. Adjective is generally Adj

**Comment by darkestkhan** [comment]
I asked because I prefer to use one terminology in code - either standard linguistic one or full words. Mixing both of them can be confusing. There is also an issue with people from countries where english is not first language - V and N can be confusing for us at first. (Adj is not much of problem - 3 letters that can be easily deduced to mean Adjective, deducing what N and V mean took me a moment [my mother tongue is Polish, and as everyone knows you should use Cz for verbs (czasownik), and Rz for nouns (rzeczownik) ;) ])

**Pull request merged**
