### PR TITLE
darkestkhan

### PR DESCRIPTION
**Pull request by darkestkhan**
Added warning switch (-Wall) and fixed two warnings.
Added style check warnings for indentation (3 spaces) and fixed all warnings triggered
(and gazed into the abyss while it gazed into me).

I plan on adding more style checks later on as making source readable is first step of paying off this technical debt.

### CODE REVIEW

**Comment by Fuco1** [comment]
Wow, does ADA really use three spaces for indent? That's insane :D

**Comment by darkestkhan** [comment]
It is Ada (Lady's name, not acronym).
And yes, standard way to indent in Ada is by 3 spaces (although many people, myself included, use 2).

I find it more insane when I see ppl using 8 spaces per indent...

**Comment by mk270** [comment]
Thanks very much for these - I've merged all but the last of these changes.

I may need some help beating Emacs into using the implied new style by default - what was there before your changes was roughly whatever vanilla ada-mode.el gives you.

**Comment by darkestkhan** [comment]
I follow "Ada Style and Quality Guide". As for emacs - no idea as to how to beat Emacs into using new style by default as I'm vim user. I suppose that ppl from #ada channel on freenode would know.

Good news is that any deviations from style checks will trigger warnings so you can always correct them.

I'm still working on remaining style checks, (ideally "-gnaty3aAbdefhiklM80nOprStux" shouldn't trigger any warnings. M80 is going to be pita to correct but it is t that that will trigger thousands of warnings - as such for now I'm going for "-gnaty3aAbdefhiklnOprSux")

**Comment by Fuco1** [comment]
@mk207 `ada-indent` is already set to 3 by default.  Also check `M-x customize-group` for `ada`.

**Comment by darkestkhan** [comment]
@mk270 Here is description of what each part of style check does: https://gcc.gnu.org/onlinedocs/gnat_ugn/Style-Checking.html (gotta love how long this flag gets...)

**Pull request closed without merging**
