### PR TITLE
Inflections package

### PR DESCRIPTION
**Pull request by darkestkhan**
Another set of changes. One of last ones, as I'm nearing completion of separating bodies.

### CODE REVIEW

**Comment by mk270** [comment]
Thanks very much once again!

I'll merge this when I get home tomorrow morning; I'm not going to be doing any of my own work on this for a day or two.

I didn't understand the reasoning in one of the commits, where a complicated function is reduced almost to a no-op. Is that going to be easy for me to work out?

Also, does the "latin_util" library as a whole have a defined set of subunits that constitute the interface it presents to its user?

**Comment by darkestkhan** [comment]
@mk270 It is hard to call "latin_util" library (when I think about library I think about coherent interface - in this case it is "just" a collection of packages used everywhere inside WORDS). Right now, as far as interface to user is concerned, it contains only ability to straight out read dictionary files and inflection data. There is more work to be done on it - like moving more packages under "latin_util" and writing actual API doc, but for now I'm just cleaning up the ones that are already there [not counting style changes there are things like fixing some nasty bugs, details are in 1b11ed5 - these bugs were bugs in waiting, not being triggered only because Whitaker didn't use correct sequence of calls necessary to cause them]

**Comment by mk270** [comment]
I reckon 050e47cb introduced a bug; try building the INFLECTS.SEC file, and see my commit.

**Comment by darkestkhan** [comment]
I will take a good look on it then. [I hope he was not testing if Last < 0...]

**Comment by darkestkhan** [comment]
I don't see where this bug comes from, and while your fix is also a bug in waiting we can use it until we understand where actually occurring bug is coming from (hints so far are: makeinfl and Inflections_Package.Ending_Record_IO.Get; I don't see where exactly this is coming from - but then again, there is too much state in makeinfl). I will open some issues regarding this and my investigation.

**Comment by mk270** [comment]
Hang on - the unmerged portion of the branch has the code that exposes the bug(s)!

**Comment by mk270** [comment]
ok - the actual bug is written up as #35 , right?

**Comment by darkestkhan** [comment]
#35 is different thing, which is still not done due to some magic happening in makeinfl. We didn't create issue about src/tools. Additionally it is still not yet fully integrated with build process - it still lacks presence in Makefile.

**Comment by darkestkhan** [comment]
Just checked  - it is still there, but at least now we don't get swamped by error messages from makeinfl.

**Comment by mk270** [comment]
what is the problem in makeinfl? is it written up in one of the tickets? (I am posssibly confused)

**Comment by darkestkhan** [comment]
That if Interjection_Record_IO.Get is set to properly work (i.e. Last is set to Source'First - 1 when nothing read) you lose 1 inflection entry.

**Comment by mk270** [comment]
fixed in fe56ec02

**Pull request closed without merging**
