### PR TITLE
+ make now reacts to changes in source files

### PR DESCRIPTION
**Pull request by Fuco1**
- missing dependencies for auxiliary programs are solved

### CODE REVIEW

**Comment by mk270** [comment]
Cheers

**Comment by Fuco1** [comment]
This took me more time than I hoped, but I already have some time booked for the next week... I'm going to dig into the `parse` package.

**Comment by mk270** [comment]
thanks - I shall see how much I can get it tidied up before then; documenting the overall organisation of the code would also be useful, but yeah, parse.adb is the epicentre of the cleanup efforts (from my perspective)

having anothe pair of shoulders and eyeballs pressing against this is really appreciated!

**Comment by mk270** [comment]
BTW, please confirm (or deny) that you're happy for your contributions to be distributed under the same terms as the programme itself.

**Comment by Fuco1** [comment]
Sure.  Though I would prefer it be GPLd but I don't think we can do that.

**Comment by mk270** [comment]
Thanks!

**Pull request merged**
