### PR TITLE
Inflections package

### PR DESCRIPTION
**Pull request by darkestkhan**
Code simplifications, deletion of commented out code, making Default_Widths constants (modifying Default_Width would break IO routines, so making them constants fixes potential issues), roll block of code under loop into loop.

### CODE REVIEW

**Comment by mk270** [comment]
Yes - OCaml probably is; I don't know the Ada type system very well.

OCaml has an idiom of strongly favouring the use of algebraic data types, which I think are equivalent to variant records in Ada. In any case, Whitaker's use of the weird union for various parts of speech makes a lot of sense to OCaml people, but I'm not sure he's got it completely right grammatically without more investigation.

**Comment by mk270** [comment]
I have merged this in part; I am declining to merge ba0b9d2 until I understand whether it is breaking basic usage tests

**Comment by darkestkhan** [comment]
ba0b9d2 doesn't break basic usage tests - it would be compile time error if it did.

**Comment by darkestkhan** [comment]
From what I saw variant records in Ada are stronger (stricter if you prefer) than in OCaml (all cases must be covered in Ada).

**Comment by mk270** [comment]
Ok, well, we now have travis integration. I'm guessing if we could trigger a build of this pull request, it'd fail?

**Comment by darkestkhan** [comment]
1) The build doesn't fail (because Default_Width is not assigned to anywhere beside initialization)
2) if you try to assign value to constant then you get compile time error
3) there is no change in output (checked it myself)

**Comment by mk270** [comment]
Ok, well, check out the branch "test-infl" - when I do make clean && make && make test, I get a failure on the test

**Comment by mk270** [comment]
Yeah, re OCaml and pattern matching - in _principle_ it is like Erlang with non-exhaustive pattern matching by default, but in practice everyone enables "non-exhaustive match is a compile time error", so much so that it's forgotten that this isn't part of the language.

The compiler error message is impressive - it makes good suggestions about what you've missed.

I'd be delighted to discover that Ada can do pattern matching on tuples, like Erlang and OCaml, but I fear this only exists in a cumbersome fashion.

**Comment by mk270** [comment]
Ok, in your code, you are initialising Noun_Record_IO.Default_Width to the expression

```
    Decn_Record_IO.Default_Width + 1 +
    Case_Type_IO.Default_Width + 1 +
    Number_Type_IO.Default_Width + 1 +
    Gender_Type_IO.Default_Width;
```

which should yield 11, but it yields 6, because Case_Type_IO.Default_Width has not been initialised to 1, and is still 0 once this code is being executed in the spec file rather than the body in `darkestkhan:inflections_package`. Case_Type_IO.Default_Width (and Number_Type etc etc) in `master` is initialised in the body, _before_ the Noun_Record_IO.Default_Width is assigned.

**Comment by mk270** [comment]
Ah, I was imprecise: this breaks the creation of the data files necessary for WORDS to run; that is only part of the "build" in a specialised sense.

**Comment by mk270** [comment]
superseded by ```default-io-width``` branch

**Pull request closed without merging**
